spring:
  application:
    name: zuul
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_IP_PORT:5996933a901a7.bj.cdb.myqcloud.com:5326}/zuul?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: ${MYSQL_NAME:root}
    password: ${MYSQL_PASS:Wu@0396110}
zuul:
  ignored-services: "*"
#  routes:
#    api-user:
#      path: /user/**
#      serviceId: user
#    api-club:
#      path: /club/**
#      serviceId: club
  host:
    maxTotalConnections: 200 #总连接数
    maxPerRouteConnections: 20  #每个路由连接数
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000 #超时
  add-host-header: true

  #prefix: /api  #为所有匹配增加前缀
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER}/eureka/
hystrix:
  metrics:
    polling-interval-ms: 2500