spring:
  application:
    name: zuul
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zuul?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
server:
  port: 9999
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/

ribbon:
  ReadTimeout: 300  #请求处理的超时时间
  ConnectTimeout: 500  #请求连接的超时时间
  SocketTimeout: 500
  #OkToRetryOnAllOperations: true  #对所有请求都开启重试
  MaxAutoRetries: 1  #对当前服务的重试次数（如果404，则再重试MaxAutoRetries次，如果还是404，则切换到其他服务)
  MaxAutoRetriesNextServer: 1  #切换服务的次数，只切换一次服务，不行就拉倒
  retryableStatusCodes: 404,502,500,408